#!/usr/bin/env python3

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt   
from mpl_toolkits.basemap import Basemap
import seaborn as sns
from tqdm import tqdm

import matplotlib as mpl
mpl.rc('font',family='Arial')

'''
all datasets for this code can be downloaded from Zenodo.org (see README for details).
'''

# plot A

# importing dataset of boolean indices indicating whether grid cell had dry lightning or not
dry_bool_cropped = np.load('dry_bool_cropped2.npy')

dates = pd.date_range(start='1/1/1987', end='12/31/2020')
dates = dates[~((dates.month == 2) & (dates.day == 29))]

drysums = np.nansum(dry_bool_cropped,axis=1)
perc = np.round((drysums/2498)*100,2) # 2498 grid cells in study domain
df = pd.DataFrame({'Date':dates,'dry_cg':perc})

df['month'] = pd.to_datetime(df.Date).dt.month
df = df[~(df.month == 1)]
df = df[~(df.month == 2)]
df = df[~(df.month == 3)]
df = df[~(df.month == 4)]
df = df[~(df.month == 11)]
df = df[~(df.month == 12)]
df1 = df[df.iloc[:,1] > 0]

percval = np.percentile(df1.iloc[:,1],95) # calculate extent corresponding to 95th percentile
df95 = df1[df1.iloc[:,1] > percval] 
index95 = np.array(df95.index.values) # index of days exceeding 95th percentile ("widespread" days)

mo_counts = [df95[df95.month==mo].shape[0] for mo in [5,6,7,8,9,10]]
# figuring out average elevations affected by widespread days in each month
surf_geo_trimmed = np.load('surf_geo_trimmed.npy')
surf_vec = np.reshape(surf_geo_trimmed,10176)

avg_elevs = []
mos = [5,6,7,8,9,10]
for k in range(6):
    mo = mos[k]
    dfx = df95[df95.month==mo]
    idxs = dfx.index.values
    mo_elevs = []
    for j in range(dfx.shape[0]):
        idx = idxs[j]
        day = dry_bool_cropped[idx,:]
        elevs = surf_vec[day==1]
        mo_elevs.append(np.nanmean(elevs))
    avg_elevs.append(np.median(mo_elevs))
        
avg_elevs = np.array(avg_elevs)
avg_elevs = (avg_elevs/1800)*5

fig = sns.catplot(x="month", y="dry_cg", kind="swarm", s=5, data=df95,
                  palette = ['tab:blue','tab:orange','c','r','y','tab:purple'])
plt.plot(avg_elevs, '-s', color='tab:brown')
plt.grid(linewidth=0.5, color='0.5', alpha=0.5, linestyle='-.')
plt.ylabel('Percent of study area', fontsize = 14)
plt.xticks(np.arange(0,6,1), ('MAY','JUN','JUL','AUG','SEP','OCT'), fontsize = 12)
plt.yticks(np.arange(0,41,5), fontsize = 12)
plt.title('(a) Seasonality of widespread dry lightning days', fontsize = 14)
fig.set(xlabel=None)
plt.axhline(y = percval, color = 'k', linestyle = '--')
plt.axhline(y = 5, color = 'tab:brown', linestyle = '--', lw=0.4)
plt.axhline(y = 5/3, color = 'tab:brown', linestyle = '--', lw=0.4)
plt.axhline(y = 5*(2/3), color = 'tab:brown', linestyle = '--', lw=0.4)
plt.tight_layout()

# plot B

# calculate maximum daily extent of dry lightning in each year
df['year'] = pd.to_datetime(df.Date).dt.year
years = np.arange(1987,2021,1)
maxvals = np.zeros(34)
for k in range(34):
    year = years[k]
    this_year = df[df.year == year]
    if this_year.shape[0] > 0:
        maxvals[k] = np.max(this_year.iloc[:,1])
        
# calculating maximum 2-day extent of widespread dry lightning

df = pd.DataFrame({'Date':dates,'dry_cells':drysums})
vec = list(df.dry_cells)
tots2day = []
for k in range(12409):
    tots2day.append(vec[k] + vec[k+1])
dates = pd.date_range(start='1/2/1987', end='12/31/2020')
dates = dates[~((dates.month == 2) & (dates.day == 29))] 
df2day = pd.DataFrame({'Ending on':dates,'dry_cells':tots2day})
df2day_sorted = df2day.sort_values(by='dry_cells', ascending=False)

cons_idx = []
priors = []
for k in tqdm(range(12408)):
    day = df2day_sorted.index[k+1]
    priors.append(df2day_sorted.index[k])
    diff1 = []
    diff2 = []
    for j in range(len(priors)):
        diff1.append(day-priors[j])
        diff2.append(priors[j]-day)
    idx1 = np.size(np.where(np.array(diff1) == 1))
    idx2 = np.size(np.where(np.array(diff2) == 1))
    if idx1 > 0 or idx2 > 0:
        cons_idx.append(1)
    else:
        cons_idx.append(0)
cons_idx.insert(0,0)  
df2day_sorted['drop_idx'] = cons_idx
df2day_sorted = df2day_sorted[df2day_sorted.drop_idx == 0]

sums2day = []
for k in range(12409):
    day1 = dry_bool_cropped[k,:]
    day2 = dry_bool_cropped[k+1,:]
    sum1 = np.nansum(day1)
    idx2 = day2[day1 == 0]
    sum2 = np.nansum(idx2)
    sums2day.append(sum1+sum2)

dates = pd.date_range(start='1/1/1987', end='12/30/2020') # shifted these by 1 day
dates = dates[~((dates.month == 2) & (dates.day == 29))] 
df2day = pd.DataFrame({'Ending on':dates,'dry_cells':sums2day})
df2day_sorted = df2day.sort_values(by='dry_cells', ascending=False)

df2day_sorted['dry_cells'] = (df2day_sorted.dry_cells/2498)*100 # convert to percentages
df2day_sorted['year'] = pd.to_datetime(df2day_sorted['Ending on']).dt.year
max2day = df2day_sorted.groupby(['year']).max()
maxs = list(max2day.iloc[:,1])

annual_widespread_days = np.load('annual_widespread_days.npy')

fig, ax1 = plt.subplots()
fig.set_size_inches(8,8)
ax1.plot(maxs, '-D', color='darkred') 
ax1.plot(maxvals, '-*', markersize=10, color='tomato')
ax1.grid(linewidth=0.5, color='0.5', alpha=0.5, linestyle='-.')
ax1.set_yticks(np.arange(0,41,5))
ax1.set_yticklabels(np.arange(0,41,5), fontsize = 17)
ax1.set_ylabel('Percent of study area', fontsize = 19)
ax1.set_ylim(top=40)
plt.title('B. Widespread dry lightning by year', size=19)
ax1.set_xticks(np.arange(0,34,1))
ax1.set_xticklabels(('','','','1990','','','','','1995','','',
               '','','2000','','','','','2005','','','','','2010','','','',
               '','2015','','','','','2020'), fontsize = 17)
plt.axhline(y = percval, color = 'k', linestyle = '--')
l = plt.legend(['Largest 2-day extent','Largest 1-day extent'], 
            loc='upper left', fontsize=18)
for text in l.get_texts():
    s = str(text)
    if int(s[20]) == 2:
        text.set_color('darkred')
    else:
        text.set_color('tomato')
ax2 = ax1.twinx()  
ax2.bar(np.arange(0,34,1), annual_widespread_days, color='cornflowerblue', alpha=0.7) 
ax2.set_yticks(np.arange(0,41,5))
ax2.set_yticklabels(['0','5','10','15','','','','',''], fontsize = 17)
ax2.set_ylabel('# of widespread days                                                       ', fontsize = 17, color='cornflowerblue')
ax2.set_ylim(top=40)
ax2.tick_params(axis='y', labelcolor='cornflowerblue')

# plot C

dates = pd.date_range(start='1/1/1987', end='12/31/2020')
dates = dates[~((dates.month == 2) & (dates.day == 29))]

drysums = np.nansum(dry_bool_cropped,axis=1)
perc = np.round((drysums/2498)*100,2) 
df = pd.DataFrame({'Date':dates,'% of grid cells with dry CG':perc})

df_ranked = df.sort_values(by='% of grid cells with dry CG',ascending=False)
df_ranked['Rank'] = np.arange(1,12411,1)
df_ranked = df_ranked[['Rank', 'Date', '% of grid cells with dry CG']] # reorder the columns to show rank first
df_ranked['month'] = pd.to_datetime(df_ranked.Date).dt.month
df_ranked = df_ranked[~(df_ranked.month == 1)]
df_ranked = df_ranked[~(df_ranked.month == 2)]
df_ranked = df_ranked[~(df_ranked.month == 3)]
df_ranked = df_ranked[~(df_ranked.month == 4)]
df_ranked = df_ranked[~(df_ranked.month == 11)]
df_ranked = df_ranked[~(df_ranked.month == 12)]

lat = np.arange(32.5-0.05,42.01-0.05,0.1)
lon = np.arange(-124.5-0.05,-113.99-0.05,0.1)
lon, lat = np.meshgrid(lon, lat)

fig = plt.figure(figsize=(6.5,12))
#plt.suptitle('10 biggest dry thunderstorm days since 1987', size=14)
for x in range(10):
    fig.add_subplot(4,5,x+1)
    var = dry_bool_cropped[df_ranked.index.values[x],:]
    summed = np.nansum(var)
    sumperc = np.round((summed/2498)*100,1)
    var = np.reshape(var,(96,106))
    #var = np.log10(var)
    m = Basemap(projection='lcc', area_thresh=10000, resolution='l',
            width=9E5, height=1.2E6,
            lat_0=37.2, lon_0=-121.5)
    m.fillcontinents(color='gray',lake_color='white',alpha=1,zorder=0)
    m.drawstates(linewidth=0.5,linestyle='solid',color='k')
    m.drawcountries(linewidth=0.5,linestyle='solid',color='k')
    m.drawcoastlines(color='black')
    m.pcolormesh(lon, lat, var, latlon=True, cmap = plt.cm.get_cmap('YlOrRd',2))
    #plt.colorbar()
    x1, y1 = m(-122.42, 37.77)
    x2, y2 = m(-122.42, 37.17)
    plt.plot(x1, y1, 'ok', markersize=5)
    plt.text(x1, y1, '   San', c='k', fontsize=5, fontweight='bold')  
    plt.text(x2, y2, '   Francisco', c='k', fontsize=5, fontweight='bold')              
    plt.title('{}) {}'.format(x+1,str(df_ranked.Date.values[x])[:10]), fontsize=10)
    #plt.text(42000,45000,'{}%'.format(sumperc), size=10)
fig.subplots_adjust(hspace = 0.2, wspace = 0)

# this code creates the inset charts showing dry lightning extent for 7 day window

df_sorted = df.sort_values(by='% of grid cells with dry CG',ascending=False)
idx10 = df_sorted.iloc[:10,:].index.values
windows7 = np.empty([10,7])
for k in range(10):
    day = idx10[k]
    sub_df = df.iloc[day-3:day+4]
    windows7[k,:] = sub_df.iloc[:,1]

days = ['21-JUN','20-JUN','3-SEP','8-AUG','30-JUL','31-AUG','16-JUN','12-AUG','17-AUG','4-OCT']

dayz = np.arange(1,11,1)
for x in range(10):
    fig = plt.figure(figsize=(6,6))
    var = windows7[x,:]
    plt.bar(np.arange(7),var,color='darkblue')
    plt.yticks(np.arange(0,31,5), ('','','','','','',''), fontsize = 50)
    plt.xticks(np.arange(7), ('-3d','','','{}'.format(days[x]),'','','+3d'), fontsize = 50)
    plt.axvline(x = 3, color = 'tab:orange', linestyle = '--', lw = 5)
    plt.axhline(y = 25, color = 'k', linestyle = '--', lw = 5)
    plt.axhline(y = 15, color = 'k', linestyle = '--', lw = 5)
    plt.axhline(y = 5, color = 'k', linestyle = '--', lw = 5)
    plt.text(-0.6,26, '25%', size=50)
    plt.text(-0.65,16, '15', size=50)
    plt.text(-0.65,6, '5', size=50)
    
 
